"""Clean -> Processed pipeline: zone-hour pickup demand aggregation.

Reads Clean taxi data (`data/clean/taxi/`), narrows it to the columns
relevant to the demand-location research question, aggregates
to (taxi_type, pu_location_id, pickup_hour) pickup counts, and constructs
explicit zero-demand rows for every (taxi_type, zone, hour) combination in
the study period that had no pickups -- a zone-hour with no observed trips
is a real "zero demand" data point for this research question, not missing
data, and the model needs to see it to learn what "no demand" looks like.

Zero-demand rows are built over the 263 real geographic taxi zones (the
TLC lookup's 265 LocationIDs minus the two non-geographic placeholders,
264 "Unknown" and 265 "Outside of NYC" -- `UNKNOWN_NA_ZONE_IDS` in
`src/clean_rules.py`) and every hour in the study period
(`STUDY_PERIOD_START` .. `STUDY_PERIOD_END_EXCLUSIVE`). This is a flagged
assumption, not a directive found elsewhere: a "zero demand" data point
only makes sense for an actual physical service area.

Historical baseline (Phase 6 step 3, locked 2026-08-16; **revised 2026-08-17
("Round 3")**): a trailing 8-week rolling mean of
`pickup_count` at each (taxi_type, zone, day-of-week, hour-of-day) slot,
computed causally per row -- using only the up-to-8 occurrences of that
exact slot strictly *before* the row's own week, never the row's own week
or any later one. Applied uniformly to every row (train and test) via the
same window computation; leakage-safe by construction regardless of
whether the prior weeks used happen to fall in the training or test
period, since a row's baseline never depends on its own or a future
observation. This deliberately differs from a "compute once at the end of
2025 and freeze" design: it mirrors how a real fleet operator would
actually have last week's observed numbers on hand before this week, and
it is the direct trigger for what makes it track a within-period demand
trend rather than flattening it into one static number. A simple
hierarchical fallback (rolling zone+dow+hour -> rolling zone+hour ->
static borough+dow+hour -> static taxi-type-wide global, the latter two
still computed once from 2024-2025 training data only) covers slots with
too little rolling history to trust -- in practice, only the very first
calendar day of the whole study period (2024-01-01) actually needs it,
since the zone+hour rolling grain already has a full window within about
a week for every zone. **Originally deferred at Phase 6** ("only revisit
if EDA/evaluation shows the static baseline is inadequate") -- revisited
after Phase 11's evaluation found exactly that: actual demand in
low-volume zones (median baseline < 10) grew roughly 3-4x relative to the
flat 2024-2025 average by 2026, almost entirely a Yellow-taxi pattern, and
no model could represent a trend the static baseline had already averaged
away. The prior static implementation is preserved, not deleted, as
`compute_static_baseline_levels`/`add_static_historical_baseline`, for
reference and comparison.

External-source join (weather/events/holidays, locked 2026-08-16):
weather joins on `pickup_hour` alone (single LGA
station, so every zone in a given hour gets the same citywide reading --
weather data ends 2026-05-30 23:00, one day short of the study period's
2026-05-31, so the last day's rows get NULL weather, a real coverage gap,
not a bug); events are expanded from their `[start_date_time,
end_date_time]` span into the hourly `(pu_location_id, pickup_hour)` cells
they cover, then joined on `(pu_location_id, pickup_hour)` to produce
`event_present`/`event_count` (no finer event detail -- deliberately kept
to just these two per user instruction); holidays are joined on calendar
date (`holiday_schedule_clean.csv`, generated by
`standardise_holiday_schedule()` from the source `holiday_schedule.csv`,
whose `Date` column is reformatted from `M/D/YY` to the same
`YYYY-MM-DD HH:MM:SS` style used everywhere else, at midnight, since a
holiday indicator applies to the whole day).

Usage:
    python -m src.processed            # yellow + green, union, write Processed
    python -m src.processed yellow     # yellow only (no union/write)
    python -m src.processed green      # green only (no union/write)
"""

from datetime import datetime, timezone
import os
from pathlib import Path
import time

from loguru import logger
import pandas as pd
from pyspark.sql import DataFrame, SparkSession, Window
from pyspark.sql import functions as F
import typer

# Must happen before the JVM starts (SparkSession.builder...getOrCreate()
# below) -- spark.sql.session.timeZone alone is not enough, since PySpark's
# collect()-to-Python datetime conversion follows the process/JVM's default
# timezone, not the Spark session conf. See the SparkSession config in
# main() for the real bug (Melbourne DST corrupting the hourly grid) this
# prevents.
os.environ["TZ"] = "UTC"
time.tzset()

from src.clean_rules import (
    STUDY_PERIOD_END_EXCLUSIVE,
    STUDY_PERIOD_START,
    UNKNOWN_NA_ZONE_IDS,
)
from src.config import (
    CLEAN_DATA_DIR,
    EXTERNAL_DATA_DIR,
    EXTERNAL_EVENTS_DIR,
    EXTERNAL_WEATHER_DIR,
    PROCESSED_DATA_DIR,
    PROJ_ROOT,
    REPORTS_DIR,
)

# If any of these turn out to be unused, flag it before dropping it from
# anything already processed, rather than silently removing it here.
PROCESSED_TAXI_COLUMNS = [
    "taxi_type",
    "pickup_datetime",
    "pu_location_id",
    "dropoff_datetime",
    "trip_duration_minutes",
    "do_location_id",
    "trip_distance",
    "passenger_count",
    "ratecode_id",
    "is_extreme_trip_distance",
    "is_extreme_trip_duration",
]


# NOTE: `source_year`/`source_month` are NOT included here even though
# `src/cleaning.py::PROVENANCE_COLUMNS` lists them -- `write_clean_dataset_per_month`
# partitions by those two columns to get one file per month, and Spark's
# `partitionBy` write drops partitioned columns from the file's own data
# (they're encoded only in the now-discarded directory structure before the
# flattening/rename step). The actual Clean parquet files on disk do not
# have these two columns; confirmed by reading a Clean file directly.
# Recoverable from the filename (`{taxi_type}-cleaned-{MM}-{YY}.parquet`)
# if ever needed. Worth fixing at the source in `src/cleaning.py` -- flagged
# to the user, not silently patched here.
PROVENANCE_COLUMNS = [
    "source_dataset",
    "source_file",
    "ingestion_timestamp",
]

TAXI_ZONE_LOOKUP_PATH = PROJ_ROOT / "resources" / "Geospatial" / "Taxi Zone Lookup.csv"
PROCESSED_DATA_QUALITY_DIR = REPORTS_DIR / "data_quality" / "processed"

# Baseline (Phase 6 step 3, locked 2026-08-16). Training period: 2024-2025
# -- this is only the leakage boundary for computing the baseline itself,
# not the formal train/test file split (that's Phase 9's job).
TRAIN_PERIOD_END_EXCLUSIVE = "2026-01-01 00:00:00"

# Rolling baseline window length (Round 3, 2026-08-17) -- the trailing number
# of prior occurrences of a (taxi_type, zone, day-of-week, hour-of-day) slot
# averaged to produce that row's baseline. The zero-demand grid guarantees
# exactly one row per slot per calendar week, so "8 prior rows" and "8 prior
# weeks" are the same thing for this grain. This is the exact "8-week"
# candidate specified (and deferred) at Phase 6.
ROLLING_BASELINE_WINDOW_WEEKS = 8

# A (taxi_type, zone, day-of-week, hour-of-day) slot needs a full trailing
# window (this many prior weeks actually present, not NULL/out-of-range) at
# ROLLING_BASELINE_WINDOW_WEEKS grain before its own rolling average is
# trusted over a coarser (less specific, more data-backed) fallback grain.
# In practice this only fails to hold for the very first ~7 weeks of the
# whole study period at any given slot -- the fallback chain below covers
# that bounded edge case, not general sparse-demand zones (a zone that is
# usually zero should still get a real near-zero rolling average, not be
# pushed to a coarser grain -- zero weeks are real signal, per this module's
# own stated philosophy, not something to fall back away from).
MIN_BASELINE_OBSERVATIONS = 8

# External-source join (Phase 6, locked 2026-08-16).
WEATHER_CLEAN_PATH = EXTERNAL_WEATHER_DIR / "lga_hourly_clean.csv"
EVENTS_CLEAN_PATH = EXTERNAL_EVENTS_DIR / "nyc_permitted_events_clean.csv"
HOLIDAY_RAW_PATH = EXTERNAL_DATA_DIR / "holiday_schedule.csv"
HOLIDAY_CLEAN_PATH = EXTERNAL_DATA_DIR / "holiday_schedule_clean.csv"


# ---------------------------------------------------------------------------
# Load + narrow
# ---------------------------------------------------------------------------


def load_clean(
    spark: SparkSession, taxi_type: str, clean_dir: Path = CLEAN_DATA_DIR / "taxi"
) -> DataFrame:
    """Read every Clean month file for one taxi type as a single DataFrame."""
    input_path = clean_dir / f"{taxi_type}-cleaned-*.parquet"
    return spark.read.parquet(str(input_path))


def narrow_to_processed_columns(df: DataFrame) -> DataFrame:
    """Select only the columns relevant to zone-hour pickup demand (+ provenance)."""
    return df.select(*PROCESSED_TAXI_COLUMNS, *PROVENANCE_COLUMNS)


# ---------------------------------------------------------------------------
# Step 1: aggregate to zone x hour pickup counts
# ---------------------------------------------------------------------------


def aggregate_to_zone_hour(df: DataFrame) -> DataFrame:
    """Group narrowed trip-level data to (taxi_type, pu_location_id, pickup_hour).

    `pickup_count` is the core target. The remaining narrowed columns don't
    survive to zone-hour grain as-is (they're per-trip), so they're
    collapsed into the summary stats that keep them meaningful at this
    grain rather than being dropped outright: mean distance/duration/
    passenger count, and a count of how many trips in that zone-hour were
    flagged extreme.
    """
    hourly = df.withColumn("pickup_hour", F.date_trunc("hour", F.col("pickup_datetime")))
    return hourly.groupBy("taxi_type", "pu_location_id", "pickup_hour").agg(
        F.count(F.lit(1)).alias("pickup_count"),
        F.avg("trip_distance").alias("avg_trip_distance"),
        F.avg("trip_duration_minutes").alias("avg_trip_duration_minutes"),
        F.avg("passenger_count").alias("avg_passenger_count"),
        F.sum(F.col("is_extreme_trip_distance").cast("int")).alias("extreme_trip_distance_count"),
        F.sum(F.col("is_extreme_trip_duration").cast("int")).alias("extreme_trip_duration_count"),
    )


# ---------------------------------------------------------------------------
# Step 2: construct explicit zero-demand rows
# ---------------------------------------------------------------------------


def load_geographic_zone_ids(lookup_path: Path = TAXI_ZONE_LOOKUP_PATH) -> list[int]:
    """TLC LocationIDs with real geometry -- excludes the non-geographic
    placeholders 264 ("Unknown") and 265 ("Outside of NYC")."""
    lookup = pd.read_csv(lookup_path)
    return sorted(int(z) for z in lookup["LocationID"] if int(z) not in UNKNOWN_NA_ZONE_IDS)


def build_zone_hour_grid(
    spark: SparkSession,
    taxi_type: str,
    zone_ids: list[int],
    start: str = STUDY_PERIOD_START,
    end_exclusive: str = STUDY_PERIOD_END_EXCLUSIVE,
) -> DataFrame:
    """Every (taxi_type, zone, hour) combination in the study period -- the
    full grid that `pickup_count` gets left-joined onto so every zone-hour
    with no observed trips is still represented, explicitly, as zero.
    """
    hours_df = spark.sql(
        f"""
        SELECT explode(sequence(
            to_timestamp('{start}'),
            to_timestamp('{end_exclusive}') - INTERVAL 1 HOUR,
            INTERVAL 1 HOUR
        )) AS pickup_hour
        """
    )
    zones_df = spark.createDataFrame([(z,) for z in zone_ids], ["pu_location_id"])
    return (
        hours_df.withColumn("taxi_type", F.lit(taxi_type))
        .crossJoin(zones_df)
        .select("taxi_type", "pu_location_id", "pickup_hour")
    )


def add_zero_demand_rows(grid_df: DataFrame, agg_df: DataFrame) -> DataFrame:
    """Left-join the grid onto the aggregate; missing `pickup_count` becomes
    0 (a real zero-demand observation). The other summary stats are left
    NULL for zero-demand rows -- there is no "average distance" of zero
    trips, and that's meaningfully different from an average of exactly 0.
    """
    joined = grid_df.join(agg_df, on=["taxi_type", "pu_location_id", "pickup_hour"], how="left")
    return joined.withColumn(
        "pickup_count", F.coalesce(F.col("pickup_count"), F.lit(0))
    ).withColumn("is_zero_demand_hour", F.col("pickup_count") == 0)


# ---------------------------------------------------------------------------
# Step 3: leakage-safe historical baseline
# ---------------------------------------------------------------------------


def add_baseline_grain_columns(df: DataFrame) -> DataFrame:
    """day_of_week (Spark's `dayofweek`: 1=Sunday..7=Saturday) and
    hour_of_day (0-23) -- the grain the baseline is averaged over."""
    return df.withColumn("day_of_week", F.dayofweek("pickup_hour")).withColumn(
        "hour_of_day", F.hour("pickup_hour")
    )


def load_zone_boroughs(
    spark: SparkSession, lookup_path: Path = TAXI_ZONE_LOOKUP_PATH
) -> DataFrame:
    """`pu_location_id` -> `borough`, used only for the coarser fallback grain."""
    lookup = pd.read_csv(lookup_path)[["LocationID", "Borough"]].rename(
        columns={"LocationID": "pu_location_id", "Borough": "borough"}
    )
    return spark.createDataFrame(lookup)


def compute_static_baseline_levels(
    train_df: DataFrame, zone_boroughs: DataFrame
) -> dict[str, DataFrame]:
    """Original (Round 1/2) static baseline: mean training-period `pickup_count`
    at each grain in the fallback chain, from most to least specific. Every
    grain is a plain average over 2024-2025 zone-hour rows (including the
    explicit zero-demand ones -- those zero weeks are real signal, not gaps
    to skip). Preserved for reference/comparison; `add_static_historical_baseline`
    (below) is the only remaining caller -- the production pipeline now uses
    the rolling baseline instead (see module docstring, "Round 3")."""
    level_zone_dow_hour = train_df.groupBy(
        "taxi_type", "pu_location_id", "day_of_week", "hour_of_day"
    ).agg(
        F.avg("pickup_count").alias("baseline_zone_dow_hour"),
        F.sum((F.col("pickup_count") > 0).cast("int")).alias("n_nonzero_weeks"),
    )
    level_zone_hour = train_df.groupBy("taxi_type", "pu_location_id", "hour_of_day").agg(
        F.avg("pickup_count").alias("baseline_zone_hour")
    )
    train_with_borough = train_df.join(zone_boroughs, on="pu_location_id", how="left")
    level_borough_dow_hour = train_with_borough.groupBy(
        "taxi_type", "borough", "day_of_week", "hour_of_day"
    ).agg(F.avg("pickup_count").alias("baseline_borough_dow_hour"))
    level_global = train_df.groupBy("taxi_type").agg(
        F.avg("pickup_count").alias("baseline_global")
    )

    return {
        "zone_dow_hour": level_zone_dow_hour,
        "zone_hour": level_zone_hour,
        "borough_dow_hour": level_borough_dow_hour,
        "global": level_global,
    }


def add_static_historical_baseline(
    df: DataFrame,
    zone_boroughs: DataFrame,
    train_period_end_exclusive: str = TRAIN_PERIOD_END_EXCLUSIVE,
    min_obs: int = MIN_BASELINE_OBSERVATIONS,
) -> DataFrame:
    """Original (Round 1/2) static-baseline pipeline step, preserved verbatim
    for reference/comparison -- see `add_historical_baseline` for the rolling
    baseline now used in production.

    Joins a leakage-safe historical baseline onto every row (train and test).
    The baseline is computed only from rows before `train_period_end_exclusive`
    (2024-2025), then joined onto the *full* dataset including 2026 -- 2026
    rows receive a baseline value without ever contributing to it. Falls back
    through zone+dow+hour -> zone+hour -> borough+dow+hour -> taxi-type-wide
    global when the most specific grain has too few non-zero training weeks
    (`min_obs`) to trust.
    """
    df = add_baseline_grain_columns(df)
    train_df = df.where(F.col("pickup_hour") < F.lit(train_period_end_exclusive))
    levels = compute_static_baseline_levels(train_df, zone_boroughs)

    df = (
        df.join(zone_boroughs, on="pu_location_id", how="left")
        .join(
            levels["zone_dow_hour"],
            on=["taxi_type", "pu_location_id", "day_of_week", "hour_of_day"],
            how="left",
        )
        .join(levels["zone_hour"], on=["taxi_type", "pu_location_id", "hour_of_day"], how="left")
        .join(
            levels["borough_dow_hour"],
            on=["taxi_type", "borough", "day_of_week", "hour_of_day"],
            how="left",
        )
        .join(levels["global"], on="taxi_type", how="left")
    )

    zone_dow_hour_reliable = F.col("n_nonzero_weeks").isNotNull() & (
        F.col("n_nonzero_weeks") >= min_obs
    )
    df = df.withColumn(
        "baseline_pickup_count",
        F.when(zone_dow_hour_reliable, F.col("baseline_zone_dow_hour"))
        .when(F.col("baseline_zone_hour").isNotNull(), F.col("baseline_zone_hour"))
        .when(F.col("baseline_borough_dow_hour").isNotNull(), F.col("baseline_borough_dow_hour"))
        .otherwise(F.col("baseline_global")),
    ).withColumn(
        "baseline_source",
        F.when(zone_dow_hour_reliable, F.lit("zone_dow_hour"))
        .when(F.col("baseline_zone_hour").isNotNull(), F.lit("zone_hour"))
        .when(F.col("baseline_borough_dow_hour").isNotNull(), F.lit("borough_dow_hour"))
        .otherwise(F.lit("global")),
    )

    return df.drop(
        "borough",
        "baseline_zone_dow_hour",
        "n_nonzero_weeks",
        "baseline_zone_hour",
        "baseline_borough_dow_hour",
        "baseline_global",
    )


def add_rolling_baseline_columns(
    df: DataFrame, window_weeks: int = ROLLING_BASELINE_WINDOW_WEEKS
) -> DataFrame:
    """Add the two rolling-window baseline candidates as row-wise columns,
    computed directly via window functions (no groupBy+join needed, unlike
    the static levels -- a window function can look "backwards" from each
    row without collapsing the frame).

    `zone_dow_hour`: partitioned by the exact (taxi_type, zone, dow, hour)
    slot, ordered by time, averaged over the trailing `window_weeks` rows.
    The zero-demand grid guarantees exactly one row per slot per calendar
    week, so `rowsBetween(-window_weeks, -1)` is exactly "the previous
    `window_weeks` occurrences of this slot", i.e. the previous
    `window_weeks` calendar weeks -- and never the row's own week, so this
    is causal/leakage-safe by construction. `n_prior_zone_dow_hour_weeks`
    counts how many rows actually fell in that trailing frame (fewer than
    `window_weeks` only near the very start of the whole study period).

    `zone_hour`: the coarser fallback grain -- same slot but pooled across
    all 7 weekdays, so the equivalent trailing time span is
    `window_weeks * 7` rows (one per day at that hour, not one per week).
    """
    w_zone_dow_hour = (
        Window.partitionBy("taxi_type", "pu_location_id", "day_of_week", "hour_of_day")
        .orderBy("pickup_hour")
        .rowsBetween(-window_weeks, -1)
    )
    w_zone_hour = (
        Window.partitionBy("taxi_type", "pu_location_id", "hour_of_day")
        .orderBy("pickup_hour")
        .rowsBetween(-window_weeks * 7, -1)
    )
    return (
        df.withColumn("baseline_zone_dow_hour", F.avg("pickup_count").over(w_zone_dow_hour))
        .withColumn("n_prior_zone_dow_hour_weeks", F.count("pickup_count").over(w_zone_dow_hour))
        .withColumn("baseline_zone_hour", F.avg("pickup_count").over(w_zone_hour))
    )


def add_historical_baseline(
    df: DataFrame,
    zone_boroughs: DataFrame,
    train_period_end_exclusive: str = TRAIN_PERIOD_END_EXCLUSIVE,
    window_weeks: int = ROLLING_BASELINE_WINDOW_WEEKS,
    min_obs: int = MIN_BASELINE_OBSERVATIONS,
) -> DataFrame:
    """Add a leakage-safe historical baseline onto every row (train and test) --
    Round 3 (2026-08-17): trailing `window_weeks`-week rolling mean, not a
    single static 2024-2025 average (see module docstring).

    Falls back through rolling zone+dow+hour -> rolling zone+hour -> static
    borough+dow+hour -> static taxi-type-wide global when the most specific
    rolling grain doesn't yet have a full trailing window
    (`n_prior_zone_dow_hour_weeks >= window_weeks`). The two coarse fallback
    levels are still the original static (train-only) computation --
    revisiting them to also be rolling was judged not worth the added
    complexity, since the static distribution showed they're essentially
    never reached (0 rows fell back that far in Round 1/2) once the two
    rolling grains are in play; they only matter for the very first
    calendar day of the study period here.
    """
    df = add_baseline_grain_columns(df)
    train_df = df.where(F.col("pickup_hour") < F.lit(train_period_end_exclusive))
    static_levels = compute_static_baseline_levels(train_df, zone_boroughs)

    df = (
        df.join(zone_boroughs, on="pu_location_id", how="left")
        .join(
            static_levels["borough_dow_hour"],
            on=["taxi_type", "borough", "day_of_week", "hour_of_day"],
            how="left",
        )
        .join(static_levels["global"], on="taxi_type", how="left")
    )
    df = add_rolling_baseline_columns(df, window_weeks=window_weeks)

    zone_dow_hour_reliable = F.col("n_prior_zone_dow_hour_weeks") >= window_weeks
    df = df.withColumn(
        "baseline_pickup_count",
        F.when(zone_dow_hour_reliable, F.col("baseline_zone_dow_hour"))
        .when(F.col("baseline_zone_hour").isNotNull(), F.col("baseline_zone_hour"))
        .when(F.col("baseline_borough_dow_hour").isNotNull(), F.col("baseline_borough_dow_hour"))
        .otherwise(F.col("baseline_global")),
    ).withColumn(
        "baseline_source",
        F.when(zone_dow_hour_reliable, F.lit("zone_dow_hour"))
        .when(F.col("baseline_zone_hour").isNotNull(), F.lit("zone_hour"))
        .when(F.col("baseline_borough_dow_hour").isNotNull(), F.lit("borough_dow_hour"))
        .otherwise(F.lit("global")),
    )

    return df.drop(
        "borough",
        "baseline_zone_dow_hour",
        "n_prior_zone_dow_hour_weeks",
        "baseline_zone_hour",
        "baseline_borough_dow_hour",
        "baseline_global",
    )


# ---------------------------------------------------------------------------
# Step 4: join external sources (weather, events, holidays)
# ---------------------------------------------------------------------------


def load_weather(spark: SparkSession, path: Path = WEATHER_CLEAN_PATH) -> DataFrame:
    """LGA hourly weather, one row per hour, already at the exact grain
    needed to join onto `pickup_hour` -- no zone dimension (citywide)."""
    return (
        spark.read.option("header", True)
        .option("inferSchema", True)
        .csv(str(path))
        .withColumn("pickup_hour", F.to_timestamp("date_hour"))
        .drop("date_hour")
    )


def join_weather(df: DataFrame, weather_df: DataFrame) -> DataFrame:
    """Left-join citywide weather onto every zone for that hour.

    Weather data ends 2026-05-30 23:00, one day short of the study period's
    2026-05-31 -- that last day's rows get NULL weather columns. A real
    coverage gap in the source data, not something to fabricate a fix for.
    """
    return df.join(weather_df, on="pickup_hour", how="left")


def load_events(spark: SparkSession, path: Path = EVENTS_CLEAN_PATH) -> DataFrame:
    """Cleaned events, restricted to those already geocoded to a taxi zone --
    events with no zone can't contribute to any zone's event count. Not all
    events geocode successfully; see the "geocoding" block written by
    `src/external_events.py::write_events_report` (or notebook `03`'s own
    printed output) for the exact current coverage rate."""
    df = (
        spark.read.option("header", True)
        .option("inferSchema", True)
        .csv(str(path))
        .where(F.col("pu_location_id").isNotNull())
    )
    return df.select(
        F.col("pu_location_id").cast("int").alias("pu_location_id"),
        F.to_timestamp("start_date_time").alias("start_date_time"),
        F.to_timestamp("end_date_time").alias("end_date_time"),
    )


def expand_events_to_zone_hour(events_df: DataFrame) -> DataFrame:
    """Expand each event's `[start_date_time, end_date_time]` span into the
    hourly `(pu_location_id, pickup_hour)` cells it covers, then collapse to
    `event_count` per cell -- an event running 00:00-23:00 the same day
    covers 24 hourly cells in the zone it's geocoded to, and a zone-hour
    with two overlapping events gets `event_count = 2`.
    """
    exploded = events_df.withColumn(
        "pickup_hour",
        F.explode(
            F.sequence(
                F.date_trunc("hour", F.col("start_date_time")),
                F.date_trunc("hour", F.col("end_date_time")),
                F.expr("INTERVAL 1 HOUR"),
            )
        ),
    )
    return exploded.groupBy("pu_location_id", "pickup_hour").agg(
        F.count(F.lit(1)).alias("event_count")
    )


def join_events(df: DataFrame, events_zone_hour_df: DataFrame) -> DataFrame:
    """Left-join per-zone-hour event counts; no match means no event (0/False),
    not missing data -- events are not taxi-type-specific, so this doesn't
    join on `taxi_type`."""
    joined = df.join(events_zone_hour_df, on=["pu_location_id", "pickup_hour"], how="left")
    return joined.withColumn("event_count", F.coalesce(F.col("event_count"), F.lit(0))).withColumn(
        "event_present", F.col("event_count") > 0
    )


def standardise_holiday_schedule(
    raw_path: Path = HOLIDAY_RAW_PATH, clean_path: Path = HOLIDAY_CLEAN_PATH
) -> pd.DataFrame:
    """Reformat the source `Date` column (`M/D/YY`, e.g. `1/1/24`) to the
    `YYYY-MM-DD HH:MM:SS` style used by every other external-data file
    (weather's `date_hour`, the taxi zone-hour grid), at midnight -- a
    holiday indicator applies to the whole day, not one specific hour.

    Two source rows can share the same calendar date -- e.g. 2025-01-20 is
    both "Birthday of Martin Luther King, Jr." and "Inauguration Day" (a
    real, once-every-4-years coincidence, not a data error). Collapsed to
    one row per date (names joined with "; ") so the later join onto the
    zone-hour table can't fan out a date's rows out to 2x.

    Writes the standardised file and also returns it (for tests).
    """
    raw = pd.read_csv(raw_path)
    raw["date"] = pd.to_datetime(raw["Date"], format="%m/%d/%y").dt.strftime("%Y-%m-%d 00:00:00")
    standardised = (
        raw.groupby("date")["Holiday"]
        .apply(lambda names: "; ".join(names))
        .reset_index()
        .rename(columns={"Holiday": "holiday_name"})
        .sort_values("date")
        .reset_index(drop=True)
    )
    clean_path.parent.mkdir(parents=True, exist_ok=True)
    standardised.to_csv(clean_path, index=False)
    logger.info(f"Wrote standardised holiday schedule to {clean_path}")
    return standardised


def load_holidays(spark: SparkSession, path: Path = HOLIDAY_CLEAN_PATH) -> DataFrame:
    """Load the standardised holiday schedule, one row per calendar date."""
    return (
        spark.read.option("header", True)
        .option("inferSchema", True)
        .csv(str(path))
        .withColumn("date", F.to_timestamp("date"))
    )


def join_holidays(df: DataFrame, holidays_df: DataFrame) -> DataFrame:
    """Left-join on calendar date (every hour of a holiday date matches)."""
    df = df.withColumn("pickup_date", F.date_trunc("day", F.col("pickup_hour")))
    holidays_df = holidays_df.withColumnRenamed("date", "pickup_date")
    joined = df.join(holidays_df, on="pickup_date", how="left")
    return joined.withColumn("is_holiday", F.col("holiday_name").isNotNull()).drop("pickup_date")


def join_external_sources(
    df: DataFrame,
    spark: SparkSession,
    weather_path: Path = WEATHER_CLEAN_PATH,
    events_path: Path = EVENTS_CLEAN_PATH,
    holiday_raw_path: Path = HOLIDAY_RAW_PATH,
    holiday_clean_path: Path = HOLIDAY_CLEAN_PATH,
) -> DataFrame:
    """Join weather, events, and holidays onto the zone-hour table (Phase 6 step 4)."""
    weather_df = load_weather(spark, weather_path)
    df = join_weather(df, weather_df)

    events_df = load_events(spark, events_path)
    events_zone_hour_df = expand_events_to_zone_hour(events_df)
    df = join_events(df, events_zone_hour_df)

    standardise_holiday_schedule(holiday_raw_path, holiday_clean_path)
    holidays_df = load_holidays(spark, holiday_clean_path)
    df = join_holidays(df, holidays_df)

    return df


# ---------------------------------------------------------------------------
# Per-taxi-type pipeline
# ---------------------------------------------------------------------------


def build_zone_hour_taxi_type(spark: SparkSession, taxi_type: str) -> dict:
    """Run the full Clean -> Processed zone-hour workflow for one taxi type."""
    clean_df = load_clean(spark, taxi_type)
    clean_row_count = clean_df.count()
    logger.info(f"[{taxi_type}] loaded {clean_row_count:,} Clean rows")

    narrowed = narrow_to_processed_columns(clean_df)
    agg_df = aggregate_to_zone_hour(narrowed)
    non_zero_row_count = agg_df.count()

    zone_ids = load_geographic_zone_ids()
    grid_df = build_zone_hour_grid(spark, taxi_type, zone_ids)
    grid_row_count = grid_df.count()

    result_df = add_zero_demand_rows(grid_df, agg_df)
    result_row_count = result_df.count()

    logger.success(
        f"[{taxi_type}] Processed zone-hour: {result_row_count:,} rows "
        f"({non_zero_row_count:,} with pickups, "
        f"{result_row_count - non_zero_row_count:,} explicit zero-demand)"
    )

    return {
        "taxi_type": taxi_type,
        "result_df": result_df,
        "clean_row_count": clean_row_count,
        "non_zero_zone_hour_count": non_zero_row_count,
        "grid_row_count": grid_row_count,
        "result_row_count": result_row_count,
    }


# ---------------------------------------------------------------------------
# Write + reporting
# ---------------------------------------------------------------------------


def write_processed_zone_hour(df: DataFrame, output_dir: Path = PROCESSED_DATA_DIR) -> Path:
    """Write the combined (Yellow + Green) zone-hour pickup table as one file."""
    output_dir.mkdir(parents=True, exist_ok=True)
    target = output_dir / "pickups_zone_hour.parquet"
    df.coalesce(1).write.mode("overwrite").parquet(str(target) + "_tmp")

    tmp_dir = Path(str(target) + "_tmp")
    part_files = list(tmp_dir.glob("part-*.parquet"))
    if len(part_files) != 1:
        raise RuntimeError(f"Expected exactly one part file in {tmp_dir}, found {len(part_files)}")
    if target.exists():
        target.unlink()
    part_files[0].rename(target)
    for leftover in tmp_dir.glob("*"):
        leftover.unlink()
    tmp_dir.rmdir()

    logger.info(f"Wrote combined Processed zone-hour dataset to {target}")
    return target


def write_report(
    results: list[dict],
    report_dir: Path = PROCESSED_DATA_QUALITY_DIR,
    baseline_source_counts: dict | None = None,
    external_join_coverage: dict | None = None,
) -> None:
    """Write the per-taxi-type Processed summary (CSV + JSON), plus the
    baseline-source distribution and external-join coverage when given."""
    report_dir.mkdir(parents=True, exist_ok=True)
    run_ts = datetime.now(timezone.utc).isoformat()
    summary_rows = [
        {
            "taxi_type": r["taxi_type"],
            "clean_row_count": r["clean_row_count"],
            "non_zero_zone_hour_count": r["non_zero_zone_hour_count"],
            "grid_row_count": r["grid_row_count"],
            "result_row_count": r["result_row_count"],
            "pct_zero_demand": round(
                100
                * (r["result_row_count"] - r["non_zero_zone_hour_count"])
                / r["result_row_count"],
                4,
            ),
        }
        for r in results
    ]
    df = pd.DataFrame(summary_rows)
    df.to_csv(report_dir / "processed_summary.csv", index=False)
    with open(report_dir / "processed_summary.json", "w") as f:
        pd.Series(
            {
                "run_timestamp": run_ts,
                "summary": summary_rows,
                "baseline_source_distribution": baseline_source_counts,
                "external_join_coverage": external_join_coverage,
            }
        ).to_json(f, indent=2)
    logger.info(f"Processed data-quality report written to {report_dir}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

app = typer.Typer()


@app.command()
def main(
    taxi_type: str = typer.Argument(
        "all",
        help="Which dataset to process: 'yellow', 'green', or 'all' (unions and writes Processed).",
    ),
):
    """Run the Clean -> Processed zone-hour aggregation pipeline."""
    if taxi_type not in {"all", "yellow", "green"}:
        raise typer.BadParameter("taxi_type must be 'all', 'yellow', or 'green'")

    spark = (
        SparkSession.builder.appName("nyc-taxi-clean-to-processed")
        .master("local[*]")
        # Pin the session timezone -- without this, Spark's date_trunc/
        # sequence/to_timestamp calls silently use the *driver machine's*
        # OS timezone, not a property of the data. On a machine set to
        # Australia/Melbourne, that machine's October DST transition
        # corrupted the hourly grid (a spring-forward gap manifested as a
        # duplicated local timestamp string), which fanned out into
        # duplicate rows once holidays/events were joined on it -- found
        # 2026-08-16. UTC has no DST, so pickup
        # timestamps (already naive/no-tz strings from the TLC data) are
        # never reinterpreted through a foreign calendar.
        .config("spark.sql.session.timeZone", "UTC")
        .config("spark.driver.memory", "16g")
        .getOrCreate()
    )
    spark.sparkContext.setLogLevel("ERROR")

    if taxi_type == "all":
        results = [
            build_zone_hour_taxi_type(spark, "yellow"),
            build_zone_hour_taxi_type(spark, "green"),
        ]
        combined_df = results[0]["result_df"].unionByName(results[1]["result_df"])

        zone_boroughs = load_zone_boroughs(spark)
        combined_df = add_historical_baseline(combined_df, zone_boroughs)
        baseline_source_counts = {
            row["baseline_source"]: row["count"]
            for row in combined_df.groupBy("baseline_source").count().collect()
        }
        logger.info(f"Baseline source distribution: {baseline_source_counts}")

        combined_df = join_external_sources(combined_df, spark)
        total_rows = combined_df.count()
        coverage_row = combined_df.agg(
            F.sum(F.col("tmpf").isNotNull().cast("int")).alias("weather_matched"),
            F.sum(F.col("event_present").cast("int")).alias("event_present_rows"),
            F.sum(F.col("is_holiday").cast("int")).alias("holiday_rows"),
        ).collect()[0]
        external_join_coverage = {
            "total_rows": total_rows,
            "weather_matched_rows": coverage_row["weather_matched"],
            "pct_weather_matched": round(100 * coverage_row["weather_matched"] / total_rows, 4),
            "event_present_rows": coverage_row["event_present_rows"],
            "pct_event_present": round(100 * coverage_row["event_present_rows"] / total_rows, 4),
            "holiday_rows": coverage_row["holiday_rows"],
            "pct_holiday": round(100 * coverage_row["holiday_rows"] / total_rows, 4),
        }
        logger.info(f"External-source join coverage: {external_join_coverage}")

        write_processed_zone_hour(combined_df)
        write_report(
            results,
            baseline_source_counts=baseline_source_counts,
            external_join_coverage=external_join_coverage,
        )
        logger.success(
            "Combined Processed zone-hour dataset: "
            f"Yellow {results[0]['result_row_count']:,} + Green {results[1]['result_row_count']:,} rows"
        )
    else:
        result = build_zone_hour_taxi_type(spark, taxi_type)
        write_report([result])
        logger.info(
            f"Ran in single-taxi-type mode ('{taxi_type}'); Processed dataset not written (use 'all')."
        )

    spark.stop()


if __name__ == "__main__":
    app()
